//! platinum-ui showcase: the living style guide, standalone.
//!
//! Uses the library's no-Tailwind path: `<PlatinumStyles/>` injects the skin
//! plus component utilities, and this crate's build.rs generates utilities
//! for the showcase's own markup (SHOWCASE_CSS below). Serve `dist/` with
//! `cargo run -p platinum-showcase-server` after `trunk build`.

mod sections;

use leptos::prelude::*;
use platinum_ui::platinum_select::PlatinumSelect;
use platinum_ui::platinum_sidebar::Sidebar;
use platinum_ui::ui_button::{Button, ButtonVariant};
use platinum_ui::{PlatinumStyles, ScrollWell};

use sections::{
    BevelsSection, ButtonsSection, ColorsSection, ContainersSection, InputsSection, ModalSection,
    ScrollingSection, TypographySection,
};

/// Utility CSS for the showcase's own classes (generated by build.rs).
const SHOWCASE_CSS: &str = include_str!(concat!(env!("OUT_DIR"), "/showcase-utilities.css"));

const CATEGORIES: [&str; 8] = [
    "Colors",
    "Bevel styles",
    "Buttons",
    "Inputs",
    "Containers",
    "Scrolling",
    "Modal",
    "Typography",
];

#[component]
fn App() -> impl IntoView {
    let selected = RwSignal::new(0usize);
    // Live bevel width (px) — drives --pl-bw for every demo at once.
    let bevel = RwSignal::new(2u32);
    // Dark palette toggle: mirrors the signal onto <html class="dark">, the
    // library's opt-in hook for its dark token set.
    let dark = RwSignal::new(false);
    Effect::new(move |_| {
        let on = dark.get();
        if let Some(root) = web_sys::window()
            .and_then(|w| w.document())
            .and_then(|d| d.document_element())
        {
            let _ = if on {
                root.class_list().add_1("dark")
            } else {
                root.class_list().remove_1("dark")
            };
        }
    });

    view! {
        <PlatinumStyles/>
        <style>{SHOWCASE_CSS}</style>

        // Fill the viewport; only the content pane's ScrollWell scrolls.
        <div class="h-screen flex flex-col overflow-hidden">
            <header class="pl-platform px-6 py-4 flex items-center gap-6 shrink-0">
                <h1 class="text-lg font-semibold tracking-tight">"platinum-ui"</h1>
                <span class="text-xs text-muted-foreground">
                    "Components inspired by the Platinum interface introduced in Mac OS 8"
                </span>
                <div class="ml-auto flex items-center gap-2">
                    // Pressed while dark — the raised group's aria-current hook.
                    <Button
                        variant=ButtonVariant::Default
                        size=platinum_ui::ui_button::ButtonSize::Sm
                        attr:aria-current=move || dark.get().then_some("page")
                        on:click=move |_| dark.update(|v| *v = !*v)
                    >"Dark"</Button>
                    <span class="text-xs text-muted-foreground uppercase tracking-wide">"Bevel size"</span>
                    <PlatinumSelect
                        min_width=96
                        selected=bevel
                        options=vec![
                            ("XS (1px)".to_string(), 1u32),
                            ("S (2px)".to_string(), 2),
                            ("M (3px)".to_string(), 3),
                            ("L (4px)".to_string(), 4),
                        ]
                    />
                </div>
            </header>

            <main class="flex-1 min-h-0 pl-platform pl-seam-top p-6 flex gap-6">
                <Sidebar
                    entries=CATEGORIES.iter().map(|s| s.to_string()).collect()
                    selected=selected
                    class="w-44 shrink-0"
                />
                // Every demo inherits the selected bevel width via --pl-bw.
                <ScrollWell class="flex-1 min-h-0">
                    <div class="p-4" style=move || format!("--pl-bw:{}px", bevel.get())>
                        // Inactive categories are hidden, not unmounted, so demo
                        // state (checkboxes, selects, the modal's one-time setup
                        // script) survives switching.
                        <div class:hidden=move || selected.get() != 0><ColorsSection/></div>
                        <div class:hidden=move || selected.get() != 1><BevelsSection/></div>
                        <div class:hidden=move || selected.get() != 2><ButtonsSection/></div>
                        <div class:hidden=move || selected.get() != 3><InputsSection/></div>
                        <div class:hidden=move || selected.get() != 4><ContainersSection/></div>
                        <div class:hidden=move || selected.get() != 5><ScrollingSection/></div>
                        <div class:hidden=move || selected.get() != 6><ModalSection/></div>
                        <div class:hidden=move || selected.get() != 7><TypographySection/></div>
                    </div>
                </ScrollWell>
            </main>
        </div>
    }
}

fn main() {
    console_error_panic_hook::set_once();
    leptos::mount::mount_to_body(App);
}
