//! platinum-ui — a Mac OS Platinum-styled **design system** for Leptos.
//!
//! This is an entire design system, not a bag of drop-in widgets: it assumes
//! it owns the whole page. Mounting it installs a global reset (Tailwind-style
//! preflight), element-level rules (buttons, inputs, headings, scrollbars),
//! and the token palette — every element on the page renders Platinum. It is
//! deliberately **all or nothing**: don't embed these components in a page
//! whose styling you don't want rewritten, and don't expect an opt-out — apps
//! either live on this system or don't use it.
//!
//! There is exactly ONE way to consume it — no Tailwind toolchain, no Node:
//! mount [`PlatinumStyles`] once near your app root. It injects
//! [`PLATINUM_CSS`] — preflight, then the hand-written skin, then utility CSS
//! for every class the components emit, generated at compile time by
//! encre-css in this crate's build.rs. Serve the `fonts/` woff2 files at your
//! web root (or accept the fallback fonts). For your app's OWN utility
//! classes, run encre-css over your sources in your app's build.rs and
//! inject the output as a second `<style>` — see `showcase/build.rs` for the
//! canonical setup.

use leptos::prelude::*;

pub mod debounce_button;
pub mod platinum_scroll;
pub mod platinum_select;
pub mod platinum_sidebar;
pub mod ui_button;
pub mod ui_collapsible;
pub mod ui_dialog;

// Flat re-exports for the common case.
pub use debounce_button::{boxed, BoxFut, DebounceButton, DEBOUNCE_MS};
pub use platinum_scroll::{PlatinumScroll, PlatinumTextarea, ScrollWell};
pub use platinum_select::PlatinumSelect;
pub use platinum_sidebar::Sidebar;
pub use ui_button::{Button, ButtonSize, ButtonVariant};
pub use ui_collapsible::{Collapsible, CollapsibleContent, CollapsibleTrigger};

/// The complete Platinum stylesheet, in cascade order:
///
/// 1. **Preflight** — the Tailwind-v4-style global reset (generated by
///    build.rs via encre-css), including the `--en-*` variable defaults that
///    composed utilities resolve against. Shipping it is what makes this a
///    design system rather than a widget library: components are written
///    against this flat baseline, never against browser UA defaults (see the
///    "preflight gap" notes in CLAUDE.md).
/// 2. **`platinum.css`** — tokens + the hand-written skin; comes after the
///    reset so its element rules win.
/// 3. **Utility CSS** for every Tailwind-compatible class the components
///    emit (generated by build.rs via encre-css) — last, so utilities win
///    over both. No Node toolchain and no consumer-side scanning involved.
pub const PLATINUM_CSS: &str = concat!(
    "/* ---- Preflight (generated by build.rs via encre-css) ---- */\n",
    include_str!(concat!(env!("OUT_DIR"), "/platinum-preflight.css")),
    "\n/* ---- Tokens + skin (platinum.css) ---- */\n",
    include_str!("../platinum.css"),
    "\n/* ---- Component utility classes (generated by build.rs via encre-css) ---- */\n",
    include_str!(concat!(env!("OUT_DIR"), "/platinum-utilities.css")),
);

/// Injects [`PLATINUM_CSS`] as a `<style>` element — the whole design system
/// in one component. Mount it once, before/above everything it styles:
///
/// ```ignore
/// view! {
///     <PlatinumStyles/>
///     <App/>
/// }
/// ```
#[component]
pub fn PlatinumStyles() -> impl IntoView {
    view! { <style>{PLATINUM_CSS}</style> }
}

/// Join a component's base utility classes with caller-supplied ones — plain
/// concatenation, deliberately NOT tw_merge: its class-name parsing mis-reads
/// design-system classes (`pl-*` → Tailwind padding-left) and silently deletes
/// them (see ui_button.rs). Base class lists are written to compose without
/// utility conflicts instead of relying on a merger to resolve them.
pub(crate) fn classes(base: &str, extra: &str) -> String {
    if extra.is_empty() {
        base.to_string()
    } else if base.is_empty() {
        extra.to_string()
    } else {
        format!("{base} {extra}")
    }
}
