//! platinum-ui — a Mac OS Platinum-styled Leptos component library.
//!
//! Components (shadcn-for-Leptos primitives reskinned Platinum, plus a few
//! custom controls). Two ways to get the styling:
//!
//! 1. **No Tailwind toolchain** (the easy path): mount [`PlatinumStyles`]
//!    once near your app root. It injects [`PLATINUM_CSS`] — the hand-written
//!    skin plus utility CSS for every class the components emit, generated at
//!    compile time by encre-css in this crate's build.rs. You still serve the
//!    `fonts/` woff2 files at your web root (or accept the fallback fonts).
//!
//! 2. **You already run Tailwind v4**: skip `PlatinumStyles`; instead
//!    `@import` this crate's `platinum.css` after Tailwind and add the
//!    crate's `src` to your `@source` scan, so your Tailwind build owns one
//!    deduplicated stylesheet (and one theme) for app + library alike.

use leptos::prelude::*;

pub mod debounce_button;
pub mod platinum_scroll;
pub mod platinum_select;
pub mod platinum_sidebar;
pub mod ui_button;
pub mod ui_collapsible;
pub mod ui_dialog;

// Flat re-exports for the common case.
pub use debounce_button::{boxed, BoxFut, DebounceButton, DEBOUNCE_MS};
pub use platinum_scroll::{PlatinumScroll, ScrollWell};
pub use platinum_select::PlatinumSelect;
pub use platinum_sidebar::Sidebar;
pub use ui_button::{Button, ButtonSize, ButtonVariant};
pub use ui_collapsible::{Collapsible, CollapsibleContent, CollapsibleTrigger};

/// The complete Platinum stylesheet: `platinum.css` (tokens + skin) followed
/// by the utility CSS for every Tailwind-compatible class the components
/// emit, generated at compile time by encre-css in build.rs — no Node
/// toolchain and no consumer-side source scanning involved.
///
/// The embedded `@theme` block is a Tailwind v4 directive; browsers ignore
/// unknown at-rules, so it's inert when this string is used directly.
pub const PLATINUM_CSS: &str = concat!(
    include_str!("../platinum.css"),
    "\n/* ---- Component utility classes (generated by build.rs via encre-css) ---- */\n",
    include_str!(concat!(env!("OUT_DIR"), "/platinum-utilities.css")),
);

/// Injects [`PLATINUM_CSS`] as a `<style>` element — the whole design system
/// in one component, for consumers not running Tailwind themselves. Mount it
/// once, before/above everything it styles:
///
/// ```ignore
/// view! {
///     <PlatinumStyles/>
///     <App/>
/// }
/// ```
///
/// Apps that already compile `platinum.css` into their own Tailwind build
/// should NOT mount this — they'd ship every rule twice.
#[component]
pub fn PlatinumStyles() -> impl IntoView {
    view! { <style>{PLATINUM_CSS}</style> }
}

/// Join a component's base utility classes with caller-supplied ones — plain
/// concatenation, deliberately NOT tw_merge: its class-name parsing mis-reads
/// design-system classes (`pl-*` → Tailwind padding-left) and silently deletes
/// them (see ui_button.rs). Base class lists are written to compose without
/// utility conflicts instead of relying on a merger to resolve them.
pub(crate) fn classes(base: &str, extra: &str) -> String {
    if extra.is_empty() {
        base.to_string()
    } else if base.is_empty() {
        extra.to_string()
    } else {
        format!("{base} {extra}")
    }
}
